apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: admin-namespace
type: Opaque
stringData:
  DB_USER: "dijkfood"
  DB_PASSWORD: "dijkfood"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
