apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: city-example-namespace
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
