apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: city-example-namespace
data:
  DB_HOST: "dijkfood.ctra4ujpjrsz.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "dijkfood"
  AWS_DEFAULT_REGION: "us-east-1"
