FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install uv

WORKDIR /app

COPY pyproject.toml uv.lock ./

# Instala TUDO (incluindo dev)
RUN uv sync --frozen

COPY . .

EXPOSE 8000

# FastAPI dev mode (auto reload)
CMD ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]