[project]
name = "admin"
version = "0.1.0"
description = "Admin service for DijkFood"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.110.0",
    "uvicorn[standard]>=0.29.0",
    "kubernetes>=29.0.0",
    "pyyaml>=6.0.1",
    "sqlalchemy>=2.0.0",
    "psycopg[binary]>=3.1.0",
    "shared",
]

[tool.uv.sources]
shared = { path = "../shared", editable = true }

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
